name: CI/CD Pipeline

on: 
  push:
    branches:
    - main

jobs:
  build-and-push:
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Docker login
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        
    - name: Build and push
      uses: docker/build-push-action@v6
      with:
        context: .
        push: true
        # You must include your Docker Hub username when pushing to Docker Hub private registry, e.g., your-dockerhub-username/my-api:latest
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/app:latest
        
        
      
    
